trigger:
- feature

pool:
  name: 'ubuntu'  # or the name of your self-hosted agent pool

variables:
  SNYK_TOKEN: $(snykApiToken)

steps:
- task: UseNode@1
  inputs:
    version: '16.x'
    
- script: npm install -g snyk
  displayName: 'Install Snyk CLI'
  
- task: SnykSecurityScan@0
  inputs:
    authToken: $(SNYK_TOKEN)
    command: test
    args: '--all-projects --severity-threshold=high --json'
  displayName: 'Run Snyk SAST Scan'
